# Generated by Django 3.0.8 on 2020-07-07 03:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=300)),
                ('cargo', models.CharField(max_length=60)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sintomatología',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mucosidad', models.CharField(max_length=2)),
                ('dolorMuscular', models.CharField(max_length=2)),
                ('sintGastrointestinal', models.CharField(max_length=2)),
                ('fechaRegistro', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('faltaAire', models.CharField(max_length=2)),
                ('temperatura', models.CharField(max_length=2)),
                ('tos', models.CharField(max_length=2)),
                ('contacto', models.CharField(max_length=2)),
                ('sintCedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado')),
            ],
        ),
    ]
