# Generated by Django 3.0.7 on 2020-06-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=300)),
                ('cargo', models.CharField(max_length=60)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
