# Generated by Django 3.0.8 on 2020-07-07 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('horaEntradaM', models.TimeField(auto_now=True)),
                ('horaSalidaM', models.TimeField(auto_now=True)),
                ('horaEntradaV', models.TimeField(auto_now=True)),
                ('horaSalidaV', models.TimeField(auto_now=True)),
                ('horasExtra', models.IntegerField()),
                ('sintCedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado')),
            ],
        ),
    ]
