# Generated by Django 3.0.8 on 2020-07-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200628_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintomatología',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mucosidad', models.CharField(max_length=2)),
                ('dolorMuscular', models.CharField(max_length=2)),
                ('sintGastrointestinal', models.CharField(max_length=2)),
                ('faltaAire', models.CharField(max_length=2)),
                ('temperatura', models.CharField(max_length=2)),
                ('tos', models.CharField(max_length=2)),
                ('contacto', models.CharField(max_length=2)),
                ('sintCedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado')),
            ],
        ),
    ]
