# Generated by Django 3.0.8 on 2020-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200712_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintomatología',
            name='contacto',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='sintomatología',
            name='dolorMuscular',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='sintomatología',
            name='faltaAire',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='sintomatología',
            name='sintGastrointestinal',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='sintomatología',
            name='temperatura',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='sintomatología',
            name='tos',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')]),
        ),
    ]
