# Generated by Django 3.0.8 on 2020-07-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horaEntradaM',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaEntradaV',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaSalidaM',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaSalidaV',
            field=models.TimeField(),
        ),
    ]
