# Generated by Django 3.0.8 on 2020-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200720_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horasExtra',
            field=models.IntegerField(default=0),
        ),
    ]
