# Generated by Django 3.0.8 on 2020-07-05 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_sintomatología'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomatología',
            name='fechaRegistro',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
